version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservices_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Eureka Service Discovery
  eureka-server:
    image: koussayblh/outdoors-app-eureka-server:latest
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # User Service
  user-service:
    image: koussayblh/outdoors-app-user-service:latest
    container_name: user-service
    restart: always
    ports:
      - "9096:9096"  
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservices_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=9096
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Camping Service
  camping-service:
    image: koussayblh/outdoors-app-camping-service:latest
    container_name: camping-service
    restart: always
    ports:
      - "9092:9092" 
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservices_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=9092
    
  # Event Service
  event-service:
    image: koussayblh/outdoors-app-event-service:latest
    container_name: event-service
    restart: always
    ports:
      - "9091:9091" 
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservices_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=9091
  
  # Formation Service
  formation-service:
    image: koussayblh/outdoors-app-formation-service:latest
    container_name: formation-service
    restart: always
    ports:
      - "9094:9094" 
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservices_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=9094
  
  # Forum Service
  forum-service:
    image: koussayblh/outdoors-app-forum-service:latest
    container_name: forum-service
    restart: always
    ports:
      - "9090:9090"     
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservices_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=9090
  
  # MarketPlace Service
  marketplace-service:
    image: koussayblh/outdoors-app-marketplace-service:latest
    container_name: marketplace-service
    restart: always
    ports:
      - "9093:9093"     
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservices_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=9093
  
  # Transport Service
  transport-service:
    image: koussayblh/outdoors-app-transport-service:latest
    container_name: transport-service
    restart: always
    ports:
      - "9095:9095"     
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservices_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=9095

  # API Gateway (if needed)
  # api-gateway:
  #   build:
  #     context: ./Back-end Microservice/Api-Gateway
  #   container_name: api-gateway
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     eureka-server:
  #       condition: service_healthy
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # Angular Frontend
  frontend:
    image: koussayblh/outdoors-app-frontend:latest
    container_name: angular-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - user-service
      - camping-service
      - event-service
      - formation-service
      - forum-service
      - marketplace-service
      - transport-service

volumes:
  mysql-data: