export enum TypeLogement {
  CHAMBRE_A_1 = 'CHAMBRE_A_1',
  CHAMBRE_A_2 = 'CHAMBRE_A_2',
  CHAMBRE_A_3 = 'CHAMBRE_A_3',
  CHAMBRE_A_4 = 'CHAMBRE_A_4',
  BANGALO_A_5 = 'BANGALO_A_5',
  BANGALO_A_10 = 'BANGALO_A_10'
}
