export enum TypeMateriel {
  MATERIEL_DE_COUCHAGE = 'MATERIEL_DE_COUCHAGE',
  MOBILIER_DE_CAMPING = 'MOBILIER_DE_CAMPING',
  CUISINE_ET_ALIMENTATION = 'CUISINE_ET_ALIMENTATION',
  EQUIPEMENT_DE_SECURITE = 'EQUIPEMENT_DE_SECURITE',
  EQUIPEMENTS_DE_LOISIRS = 'EQUIPEMENTS_DE_LOISIRS'
}
